using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PGK.Extensions
{
    /// <summary>
    /// Enumeration of all CultureInfo Names using the DisplayStringAttribute to allow 
    /// developer to easily specify a culture from an enumeration.
    /// </summary>
    public enum Cultures
    {
        // ReSharper disable InconsistentNaming
#pragma warning disable 1591
        [DisplayString("af-ZA")]
        Afrikaans,
        [DisplayString("af-ZA")]
        Afrikaans_SouthAfrica,
        [DisplayString("ar-SA")]
        Arabic,
        [DisplayString("ar-AE")]
        Arabic_Uae,
        [DisplayString("ar-BH")]
        Arabic_Bahrain,
        [DisplayString("ar-DZ")]
        Arabic_Algeria,
        [DisplayString("ar-EG")]
        Arabic_Egypt,
        [DisplayString("ar-IQ")]
        Arabic_Iraq,
        [DisplayString("ar-JO")]
        Arabic_Jordan,
        [DisplayString("ar-KW")]
        Arabic_Kuwait,
        [DisplayString("ar-LB")]
        Arabic_Lebanon,
        [DisplayString("ar-LY")]
        Arabic_Libya,
        [DisplayString("ar-MA")]
        Arabic_Morocco,
        [DisplayString("ar-OM")]
        Arabic_Oman,
        [DisplayString("ar-QA")]
        Arabic_Qatar,
        [DisplayString("ar-SA")]
        Arabic_SaudiArabia,
        [DisplayString("ar-SY")]
        Arabic_Syria,
        [DisplayString("ar-TN")]
        Arabic_Tunisia,
        [DisplayString("ar-YE")]
        Arabic_Yemen,
        [DisplayString("az-Latn-AZ")]
        Azeri,
        [DisplayString("az-Cyrl-AZ")]
        Azeri_Cyrillic_Azerbaijan,
        [DisplayString("az-Latn-AZ")]
        Azeri_Latin_Azerbaijan,
        [DisplayString("be-BY")]
        Belarusian,
        [DisplayString("be-BY")]
        Belarusian_Belarus,
        [DisplayString("bg-BG")]
        Bulgarian,
        [DisplayString("bg-BG")]
        Bulgarian_Bulgaria,
        [DisplayString("bs-Latn-BA")]
        Bosnian_Bosnia_and_Herzegovina,
        [DisplayString("ca-ES")]
        Catalan,
        [DisplayString("ca-ES")]
        Catalan_Catalan,
        [DisplayString("cs-CZ")]
        Czech,
        [DisplayString("cs-CZ")]
        Czech_CzechRepublic,
        [DisplayString("cy-GB")]
        Welsh_UnitedKingdom,
        [DisplayString("da-DK")]
        Danish,
        [DisplayString("da-DK")]
        Danish_Denmark,
        [DisplayString("de-DE")]
        German,
        [DisplayString("de-AT")]
        German_Austria,
        [DisplayString("de-DE")]
        German_Germany,
        [DisplayString("de-CH")]
        German_Switzerland,
        [DisplayString("de-LI")]
        German_Liechtenstein,
        [DisplayString("de-LU")]
        German_Luxembourg,
        [DisplayString("dv-MV")]
        Divehi,
        [DisplayString("dv-MV")]
        Divehi_Maldives,
        [DisplayString("el-GR")]
        Greek,
        [DisplayString("el-GR")]
        Greek_Greece,
        [DisplayString("en-US")]
        English,
        [DisplayString("en-029")]
        English_Caribbean,
        [DisplayString("en-AU")]
        English_Australia,
        [DisplayString("en-BZ")]
        English_Belize,
        [DisplayString("en-CA")]
        English_Canada,
        [DisplayString("en-GB")]
        English_UnitedKingdom,
        [DisplayString("en-IE")]
        English_Ireland,
        [DisplayString("en-JM")]
        English_Jamaica,
        [DisplayString("en-NZ")]
        English_NewZealand,
        [DisplayString("en-PH")]
        English_RepublicOfThePhilippines,
        [DisplayString("en-TT")]
        English_Trinidad_and_Tobago,
        [DisplayString("en-US")]
        English_UnitedStates,
        [DisplayString("en-ZA")]
        English_SouthAfrica,
        [DisplayString("en-ZW")]
        English_Zimbabwe,
        [DisplayString("es-ES")]
        Spanish,
        [DisplayString("es-AR")]
        Spanish_Argentina,
        [DisplayString("es-BO")]
        Spanish_Bolivia,
        [DisplayString("es-CL")]
        Spanish_Chile,
        [DisplayString("es-CO")]
        Spanish_Colombia,
        [DisplayString("es-CR")]
        Spanish_CostaRica,
        [DisplayString("es-DO")]
        Spanish_DominicanRepublic,
        [DisplayString("es-EC")]
        Spanish_Ecuador,
        [DisplayString("es-ES")]
        Spanish_Spain,
        [DisplayString("es-GT")]
        Spanish_Guatemala,
        [DisplayString("es-HN")]
        Spanish_Honduras,
        [DisplayString("es-MX")]
        Spanish_Mexico,
        [DisplayString("es-NI")]
        Spanish_Nicaragua,
        [DisplayString("es-PA")]
        Spanish_Panama,
        [DisplayString("es-PE")]
        Spanish_Peru,
        [DisplayString("es-PR")]
        Spanish_PuertoRico,
        [DisplayString("es-PY")]
        Spanish_Paraguay,
        [DisplayString("es-SV")]
        Spanish_ElSalvador,
        [DisplayString("es-UY")]
        Spanish_Uruguay,
        [DisplayString("es-VE")]
        Spanish_Venezuela,
        [DisplayString("et-EE")]
        Estonian,
        [DisplayString("et-EE")]
        Estonian_Estonia,
        [DisplayString("eu-ES")]
        Basque,
        [DisplayString("eu-ES")]
        Basque_Basque,
        [DisplayString("fa-IR")]
        Persian,
        [DisplayString("fa-IR")]
        Persian_Iran,
        [DisplayString("fi-FI")]
        Finnish,
        [DisplayString("fi-FI")]
        Finnish_Finland,
        [DisplayString("fo-FO")]
        Faroese,
        [DisplayString("fo-FO")]
        Faroese_FaroeIslands,
        [DisplayString("fr-FR")]
        French,
        [DisplayString("fr-BE")]
        French_Belgium,
        [DisplayString("fr-CA")]
        French_Canada,
        [DisplayString("fr-FR")]
        French_France,
        [DisplayString("fr-CH")]
        French_Switzerland,
        [DisplayString("fr-LU")]
        French_Luxembourg,
        [DisplayString("fr-MC")]
        French_PrincipalityOfMonaco,
        [DisplayString("gl-ES")]
        Galician,
        [DisplayString("gl-ES")]
        Galician_Galician,
        [DisplayString("gu-IN")]
        Gujarati,
        [DisplayString("gu-IN")]
        Gujarati_India,
        [DisplayString("he-IL")]
        Hebrew,
        [DisplayString("he-IL")]
        Hebrew_Israel,
        [DisplayString("hi-IN")]
        Hindi,
        [DisplayString("hi-IN")]
        Hindi_India,
        [DisplayString("hr-HR")]
        Croatian,
        [DisplayString("hr-BA")]
        Croatian_Bosnia_and_Herzegovina,
        [DisplayString("hr-HR")]
        Croatian_Croatia,
        [DisplayString("hu-HU")]
        Hungarian,
        [DisplayString("hu-HU")]
        Hungarian_Hungary,
        [DisplayString("hy-AM")]
        Armenian,
        [DisplayString("hy-AM")]
        Armenian_Armenia,
        [DisplayString("id-ID")]
        Indonesian,
        [DisplayString("id-ID")]
        Indonesian_Indonesia,
        [DisplayString("is-IS")]
        Icelandic,
        [DisplayString("is-IS")]
        Icelandic_Iceland,
        [DisplayString("it-IT")]
        Italian,
        [DisplayString("it-CH")]
        Italian_Switzerland,
        [DisplayString("it-IT")]
        Italian_Italy,
        [DisplayString("ja-JP")]
        Japanese,
        [DisplayString("ja-JP")]
        Japanese_Japan,
        [DisplayString("ka-GE")]
        Georgian,
        [DisplayString("ka-GE")]
        Georgian_Georgia,
        [DisplayString("kk-KZ")]
        Kazakh,
        [DisplayString("kk-KZ")]
        Kazakh_Kazakhstan,
        [DisplayString("kn-IN")]
        Kannada,
        [DisplayString("kn-IN")]
        Kannada_India,
        [DisplayString("ko-KR")]
        Korean,
        [DisplayString("kok-IN")]
        Konkani,
        [DisplayString("kok-IN")]
        Konkani_India,
        [DisplayString("ko-KR")]
        Korean_Korea,
        [DisplayString("ky-KG")]
        Kyrgyz,
        [DisplayString("ky-KG")]
        Kyrgyz_Kyrgyzstan,
        [DisplayString("lt-LT")]
        Lithuanian,
        [DisplayString("lt-LT")]
        Lithuanian_Lithuania,
        [DisplayString("lv-LV")]
        Latvian,
        [DisplayString("lv-LV")]
        Latvian_Latvia,
        [DisplayString("mi-NZ")]
        Maori_NewZealand,
        [DisplayString("mk-MK")]
        Macedonian,
        [DisplayString("mk-MK")]
        Macedonian_FormerYugoslavRepublicOfMacedonia,
        [DisplayString("mn-MN")]
        Mongolian,
        [DisplayString("mn-MN")]
        Mongolian_Cyrillic_Mongolia,
        [DisplayString("mr-IN")]
        Marathi,
        [DisplayString("mr-IN")]
        Marathi_India,
        [DisplayString("ms-MY")]
        Malay,
        [DisplayString("ms-BN")]
        Malay_Brunei_Darussalam,
        [DisplayString("ms-MY")]
        Malay_Malaysia,
        [DisplayString("mt-MT")]
        Maltese_Malta,
        [DisplayString("nb-NO")]
        Norwegian_Bokmal_Norway,
        [DisplayString("nl-NL")]
        Dutch,
        [DisplayString("nl-BE")]
        Dutch_Belgium,
        [DisplayString("nl-NL")]
        Dutch_Netherlands,
        [DisplayString("nn-NO")]
        Norwegian_Nynorsk_Norway,
        [DisplayString("nb-NO")]
        Norwegian,
        [DisplayString("ns-ZA")]
        Northern_Sotho_SouthAfrica,
        [DisplayString("pa-IN")]
        Punjabi,
        [DisplayString("pa-IN")]
        Punjabi_India,
        [DisplayString("pl-PL")]
        Polish,
        [DisplayString("pl-PL")]
        Polish_Poland,
        [DisplayString("pt-BR")]
        Portuguese,
        [DisplayString("pt-BR")]
        Portuguese_Brazil,
        [DisplayString("pt-PT")]
        Portuguese_Portugal,
        [DisplayString("quz-BO")]
        Quechua_Bolivia,
        [DisplayString("quz-EC")]
        Quechua_Ecuador,
        [DisplayString("quz-PE")]
        Quechua_Peru,
        [DisplayString("ro-RO")]
        Romanian,
        [DisplayString("ro-RO")]
        Romanian_Romania,
        [DisplayString("ru-RU")]
        Russian,
        [DisplayString("ru-RU")]
        Russian_Russia,
        [DisplayString("sa-IN")]
        Sanskrit,
        [DisplayString("sa-IN")]
        Sanskrit_India,
        [DisplayString("se-FI")]
        Sami_Northern_Finland,
        [DisplayString("se-NO")]
        Sami_Northern_Norway,
        [DisplayString("se-SE")]
        Sami_Northern_Sweden,
        [DisplayString("sk-SK")]
        Slovak,
        [DisplayString("sk-SK")]
        Slovak_Slovakia,
        [DisplayString("sl-SI")]
        Slovenian,
        [DisplayString("sl-SI")]
        Slovenian_Slovenia,
        [DisplayString("sma-NO")]
        Sami_Southern_Norway,
        [DisplayString("sma-SE")]
        Sami_Southern_Sweden,
        [DisplayString("smj-NO")]
        Sami_Lule_Norway,
        [DisplayString("smj-SE")]
        Sami_Lule_Sweden,
        [DisplayString("smn-FI")]
        Sami_Inari_Finland,
        [DisplayString("sms-FI")]
        Sami_Skolt_Finland,
        [DisplayString("sq-AL")]
        Albanian,
        [DisplayString("sq-AL")]
        Albanian_Albania,
        [DisplayString("sr-Latn-CS")]
        Serbian,
        [DisplayString("sr-Cyrl-BA")]
        Serbian_Cyrillic_BosniaAndHerzegovina,
        [DisplayString("sr-Cyrl-CS")]
        Serbian_Cyrillic_Serbia,
        [DisplayString("sr-Latn-BA")]
        Serbian_Latin_Bosnia_and_Herzegovina,
        [DisplayString("sr-Latn-CS")]
        Serbian_Latin_Serbia,
        [DisplayString("sv-SE")]
        Swedish,
        [DisplayString("sv-FI")]
        Swedish_Finland,
        [DisplayString("sv-SE")]
        Swedish_Sweden,
        [DisplayString("sw-KE")]
        Kiswahili,
        [DisplayString("sw-KE")]
        Kiswahili_Kenya,
        [DisplayString("syr-SY")]
        Syriac,
        [DisplayString("syr-SY")]
        Syriac_Syria,
        [DisplayString("ta-IN")]
        Tamil,
        [DisplayString("ta-IN")]
        Tamil_India,
        [DisplayString("te-IN")]
        Telugu,
        [DisplayString("te-IN")]
        Telugu_India,
        [DisplayString("th-TH")]
        Thai,
        [DisplayString("th-TH")]
        Thai_Thailand,
        [DisplayString("tn-ZA")]
        Tswana_SouthAfrica,
        [DisplayString("tr-TR")]
        Turkish,
        [DisplayString("tr-TR")]
        Turkish_Turkey,
        [DisplayString("tt-RU")]
        Tatar,
        [DisplayString("tt-RU")]
        Tatar_Russia,
        [DisplayString("uk-UA")]
        Ukrainian,
        [DisplayString("uk-UA")]
        Ukrainian_Ukraine,
        [DisplayString("ur-PK")]
        Urdu,
        [DisplayString("ur-PK")]
        Urdu_IslamicRepublicOfPakistan,
        [DisplayString("uz-Latn-UZ")]
        Uzbek,
        [DisplayString("uz-Cyrl-UZ")]
        Uzbek_Cyrillic_Uzbekistan,
        [DisplayString("uz-Latn-UZ")]
        Uzbek_Latin_Uzbekistan,
        [DisplayString("vi-VN")]
        Vietnamese,
        [DisplayString("vi-VN")]
        Vietnamese_Vietnam,
        [DisplayString("xh-ZA")]
        Xhosa_SouthAfrica,
        [DisplayString("zh-Hans")]
        Chinese_Simplified,
        [DisplayString("zh-Hant")]
        Chinese_Traditional,
        [DisplayString("zh-CN")]
        Chinese_PeoplesRepublicOfChina,
        [DisplayString("zh-HK")]
        Chinese_HongKongSAR,
        [DisplayString("zh-MO")]
        Chinese_MacaoSAR,
        [DisplayString("zh-SG")]
        Chinese_Singapore,
        [DisplayString("zh-TW")]
        Chinese_Taiwan,
        [DisplayString("zu-ZA")]
        Zulu_SouthAfrica
        // ReSharper restore InconsistentNaming
#pragma warning restore 1591
    }
}
